sudo: required

services:
- docker

language: go

go:
- "1.10"

go_import_path: github.com/container-mgmt/dedicated-portal

install:
- go get github.com/golang/dep/cmd/dep
- go get golang.org/x/lint/golint
- go get github.com/client9/misspell/cmd/misspell

script:
# Check for `go fmt` errors
- if [ $(gofmt -s -l ./pkg/ ./cmd/ | wc -l) -eq 0 ]; then true; else false; fi;
# Check for `golint` errors
- make lint
# Check for common misspell errors (this is not a speller)
- misspell -error cmd/** pkg/** README.adoc
# Check that everything compiles
- make images
